// <auto-generated />
using System;
using Avaliacao.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avaliacao.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextAvaliacao))]
    [Migration("20260210131004_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avaliacao.Domain.Entities.Segurado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do segurado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasComment("CPF do segurado");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasComment("Idade do segurado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nome do segurado");

                    b.HasKey("Id");

                    b.ToTable("Segurado", null, t =>
                        {
                            t.HasComment("Tabela de segurados");
                        });
                });

            modelBuilder.Entity("Avaliacao.Domain.Entities.Seguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificador único do seguro");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de criação do seguro em UTC");

                    b.Property<decimal>("PremioComercial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Prêmio comercial final");

                    b.Property<decimal>("PremioPuro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Prêmio puro calculado");

                    b.Property<decimal>("PremioRisco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Prêmio de risco calculado");

                    b.Property<int>("SeguradoId")
                        .HasColumnType("int")
                        .HasComment("Identificador do segurado");

                    b.Property<decimal>("TaxaRisco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Taxa de risco aplicada");

                    b.Property<decimal>("ValorSeguro")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor total do seguro");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasComment("Identificador do veículo segurado");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Seguro", null, t =>
                        {
                            t.HasComment("Tabela de seguros");
                        });
                });

            modelBuilder.Entity("Avaliacao.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do veículo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Marca e modelo do veículo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor do veículo");

                    b.HasKey("Id");

                    b.ToTable("Veiculo", null, t =>
                        {
                            t.HasComment("Tabela de veículos");
                        });
                });

            modelBuilder.Entity("Avaliacao.Domain.Entities.Seguro", b =>
                {
                    b.HasOne("Avaliacao.Domain.Entities.Segurado", "Segurado")
                        .WithMany()
                        .HasForeignKey("SeguradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avaliacao.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Segurado");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
